name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests et Validation

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Exécuter ESLint
        run: npm run lint

      - name: Exécuter les tests
        run: npm run test

  deploy:
    needs: test  # Dépend du job "test"
    if: success()  # S'exécute seulement si les tests passent
    runs-on: ubuntu-latest
    name: Déploiement sur Render
    
    steps:
      - name: Déclencher le déploiement Render
        uses: sws2apps/render-deployment@main
        with:
          serviceId: ${{ rnd_CrkR7Rbui54ZdbpW59tDBrx54pE0 }}
          apiKey: ${{ srv-d5pi8dn5c7fs73bngfvg }}